model = dict(
    type='DAS',
    pretrained='open-mmlab://detectron2/resnet50_caffe',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, False, False, False),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        style='caffe'
    ),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5,
        relu_before_extra_convs=True),
    bbox_head=dict(
        type='DASHead',
        num_classes=1,
        in_channels=256,
        stacked_convs=2,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        center_sample_radius=1.5,
        num_joints=15,
        cls_branch=(256, ),
        reg_branch=(
            (256, ),
            (256, ),
            (256, ),
            (256, ),
        ),
        centerness_on_reg=True,
        conv_bias=True,
        dcn_on_last_conv=True,
        recursive_update=dict(
            prev_loss=True,
            num_heads=4,
            in_channels=256,
            feat_channels=256,
            num_layers=1,
            dim=3,
        ),
    ),
)
